name: Test Build

on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - ./github/**
      - README.md
      - LICENCE

jobs:
  test_build:
    name: Build & run tests
    runs-on: ubuntu-latest
    env:
      SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Decrypt secrets
        run: openssl aes-256-cbc -d -pass env:SECRET_PASSWORD -salt -pbkdf2 -in app/secrets.enc -out app/secrets.tar.gz